version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres_password
    ports:
      - 15432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
