CREATE DATABASE ems;
CREATE USER ems_user WITH ENCRYPTED PASSWORD 'ems_password';
GRANT ALL PRIVILEGES ON DATABASE ems TO ems_user;
\c ems
GRANT USAGE ON SCHEMA public TO ems_user;
GRANT CREATE ON SCHEMA public TO ems_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ems_user;
