spring:
  profiles:
    default: h2
  main:
    banner-mode: off
  shell:
    interactive:
      enabled: true
  flyway:
    schemas: ems
    placeholders:
      jsonType: JSONB
logging:
  level:
    root: off
