spring:
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS ems
    driverClassName: org.h2.Driver
    username: sa
    password: password
  flyway:
    placeholders:
      jsonType: TEXT
